# Generated by Django 5.2.3 on 2025-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_member_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
