# Generated by Django 5.2.3 on 2025-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
