# Generated by Django 5.2.3 on 2025-07-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
